export const cities = [
  { name: "Aberdeen", slug: "aberdeen" },
  { name: "Abilene", slug: "abilene" },
  { name: "Akron", slug: "akron" },
  { name: "Albany", slug: "albany" },
  { name: "Albuquerque", slug: "albuquerque" },
  { name: "Alexandria", slug: "alexandria" },
  { name: "Allentown", slug: "allentown" },
  { name: "Amarillo", slug: "amarillo" },
  { name: "Anaheim", slug: "anaheim" },
  { name: "Anchorage", slug: "anchorage" },
  { name: "Ann Arbor", slug: "ann-arbor" },
  { name: "Antioch", slug: "antioch" },
  { name: "Apple Valley", slug: "apple-valley" },
  { name: "Appleton", slug: "appleton" },
  { name: "Arlington", slug: "arlington" },
  { name: "Arvada", slug: "arvada" },
  { name: "Asheville", slug: "asheville" },
  { name: "Athens", slug: "athens" },
  { name: "Atlanta", slug: "atlanta" },
  { name: "Atlantic City", slug: "atlantic-city" },
  { name: "Augusta", slug: "augusta" },
  { name: "Aurora", slug: "aurora" },
  { name: "Austin", slug: "austin" },
  { name: "Bakersfield", slug: "bakersfield" },
  { name: "Baltimore", slug: "baltimore" },
  { name: "Barnstable", slug: "barnstable" },
  { name: "Baton Rouge", slug: "baton-rouge" },
  { name: "Beaumont", slug: "beaumont" },
  { name: "Bel Air", slug: "bel air" },
  { name: "Bellevue", slug: "bellevue" },
  { name: "Berkeley", slug: "berkeley" },
  { name: "Bethlehem", slug: "bethlehem" },
  { name: "Billings", slug: "billings" },
  { name: "Birmingham", slug: "birmingham" },
  { name: "Bloomington", slug: "bloomington" },
  { name: "Boise", slug: "boise" },
  { name: "Boise City", slug: "boise-city" },
  { name: "Bonita Springs", slug: "bonita-springs" },
  { name: "Boston", slug: "boston" },
  { name: "Boulder", slug: "boulder" },
  { name: "Bradenton", slug: "bradenton" },
  { name: "Bremerton", slug: "bremerton" },
  { name: "Bridgeport", slug: "bridgeport" },
  { name: "Brighton", slug: "brighton" },
  { name: "Brownsville", slug: "brownsville" },
  { name: "Bryan", slug: "bryan" },
  { name: "Buffalo", slug: "buffalo" },
  { name: "Burbank", slug: "burbank" },
  { name: "Burlington", slug: "burlington" },
  { name: "Cambridge", slug: "cambridge" },
  { name: "Canton", slug: "canton" },
  { name: "Cape Coral", slug: "cape-coral" },
  { name: "Carrollton", slug: "carrollton" },
  { name: "Cary", slug: "cary" },
  { name: "Cathedral City", slug: "cathedral-city" },
  { name: "Cedar Rapids", slug: "cedar-rapids" },
  { name: "Champaign", slug: "champaign" },
  { name: "Chandler", slug: "chandler" },
  { name: "Charleston", slug: "charleston" },
  { name: "Charlotte", slug: "charlotte" },
  { name: "Chattanooga", slug: "chattanooga" },
  { name: "Chesapeake", slug: "chesapeake" },
  { name: "Chicago", slug: "chicago" },
  { name: "Chula Vista", slug: "chula vista" },
  { name: "Cincinnati", slug: "cincinnati" },
  { name: "Clarke County", slug: "clarke-county" },
  { name: "Clarksville", slug: "clarksville" },
  { name: "Clearwater", slug: "clearwater" },
  { name: "Cleveland", slug: "cleveland" },
  { name: "College Station", slug: "college-station" },
  { name: "Colorado Springs", slug: "colorado-springs" },
  { name: "Columbia", slug: "columbia" },
  { name: "Columbus", slug: "columbus" },
  { name: "Concord", slug: "concord" },
  { name: "Coral Springs", slug: "coral-springs" },
  { name: "Corona", slug: "corona" },
  { name: "Corpus Christi", slug: "corpus-christi" },
  { name: "Costa Mesa", slug: "costa-mesa" },
  { name: "Dallas", slug: "dallas" },
  { name: "Daly City", slug: "daly-city" },
]
